### PR TITLE
Restore Go 1.11 support

### PR DESCRIPTION
**Pull request by rfjakob**
"errors.Is()" need Go 1.13 and higher. We can do with
a plain "==" here and keep Go 1.11 support without a problem.

Also add Go 1.11+ back to Travis.

See the discussion at
https://github.com/pkg/xattr/commit/994316708194a4ca6198b54c879dc5881ca59c71#r44193396
for details.

### CODE REVIEW

**Comment by rfjakob** [comment]
Hmm, more problems on Go 1.11 ( https://travis-ci.org/github/pkg/xattr/jobs/743736667 ):
```
Building for Darwin...
# golang.org/x/sys/unix
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/fcntl_darwin.go:11:9: undefined: fcntl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/fcntl_darwin.go:16:12: undefined: fcntl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/fcntl_darwin.go:22:12: undefined: fcntl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:20:9: undefined: ioctl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:29:9: undefined: ioctl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:38:9: undefined: ioctl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:48:9: undefined: ioctl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:60:9: undefined: ioctl
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/syscall_bsd.go:645:10: undefined: mmap
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/syscall_bsd.go:646:10: undefined: munmap
../../../../pkg/mod/golang.org/x/sys@v0.0.0-20201101102859-da207088b7d1/unix/ioctl.go:60:9: too many errors
The command "./.travis.sh" exited with 2.
```
Maybe it's too much of a hassle after all. I'll close the PR and update cshatag to build using Go 1.14.
